package com.byte4b.judebo.models

data class MyMarker(
    val ALL_SKILLS_NAME: String,
    val AUTO_TRANSLATE: Int,
    val COMPANY: String = "",
    val DETAIL_TEXT: String,
    val ID: Int,
    val NAME: String,
    val UF_CONTACT_EMAIL: String,
    val UF_CONTACT_PHONE: String,
    val UF_DETAIL_IMAGE: String,
    val UF_DISABLE: String,
    val UF_GOLD_GROSS_MONTH: String,
    val UF_GOLD_PER_MONTH: String,
    val UF_GROSS_CURRENCY_ID: Int,
    val UF_GROSS_PER_MONTH: String,
    val UF_JOBS_ID: Int,
    val UF_LANGUAGE_ID_ALL: String,
    val UF_TYPE_OF_JOB_NAME: String? = null,
    val UF_LOGO_IMAGE: String? = null,
    val UF_MAP_POINT: String,
    var UF_MAP_POINT_LATITUDE: Double,
    var UF_MAP_POINT_LONGITUDE: Double,
    val UF_MAP_RENDERED: Int,
    val UF_MODIFED: String,
    val UF_PREVIEW_IMAGE: String,
    val UF_SKILLS_ID_ALL: String,
    val UF_TYPE_OF_JOB_ID: Int
)